### ISSUE TITLE
 Failed to clone https://github.com/Slynova-Org/laravel-commentable.git

### ISSUE THREAD

**Issue by illuminate3** [UnrulyNatives/laravel-starter-kit-and-snippets#2]
Try this: https://github.com/thyagobrejao/laravel-commentable

**Comment by UnrulyNatives** [comment]
I will deal with it tomorrow. In other projects I resorted to manually uploading the package into `vendor` dir. As long as the package version is not updated in `composer.json`, the dirty fix persists. 

Thank you.

**Comment by illuminate3** [comment]
I was just playing with your repo and I happen to use that package for projects on 5.1. That repo seems to be a fork of the slynova one and just renamed.

**Comment by UnrulyNatives** [comment]
Done. 

Thank you for suggestion
